//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBSSGK.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bm_dutyposts
    {
        public int postid { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> seqno { get; set; }
        public Nullable<int> regiontypeid { get; set; }
        public string postname { get; set; }
        public string postcode { get; set; }
        public string postdesc { get; set; }
    }
}
