//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBSSGK.ZHCG.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mapelementbiztype> mapelementbiztypes { get; set; }
        public DbSet<unit> units { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<userstarstat> userstarstats { get; set; }
        public DbSet<mapelement> mapelements { get; set; }
        public DbSet<region> regions { get; set; }
        public DbSet<bm_carpatrollines> bm_carpatrollines { get; set; }
        public DbSet<bm_carpatrolplans> bm_carpatrolplans { get; set; }
        public DbSet<bm_dutyplans> bm_dutyplans { get; set; }
        public DbSet<bm_dutypostmappings> bm_dutypostmappings { get; set; }
        public DbSet<bm_dutyposts> bm_dutyposts { get; set; }
        public DbSet<bm_dutyusers> bm_dutyusers { get; set; }
        public DbSet<bm_userpatrollines> bm_userpatrollines { get; set; }
        public DbSet<bm_userpatrolplans> bm_userpatrolplans { get; set; }
    }
}
