//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBSSGK.ZHCG.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class userstarstat
    {
        public int STATID { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public int USERID { get; set; }
        public int UNITID { get; set; }
        public int REGIONID { get; set; }
        public int EVENTNUM { get; set; }
        public Nullable<System.DateTime> STATDATE { get; set; }
        public string SEX { get; set; }
        public string USERNAME { get; set; }
        public string REGIONNAME { get; set; }
        public string PHOTOURL { get; set; }
        public Nullable<int> mapelementbiztypesid { get; set; }
    }
}
